version: '3.9'
volumes:
  pgdata:
    driver: local
    name: pg_docker

# Postgresql
services:
  db:
    image: postgres
    container_name: pg_db
    restart: always
    env_file:
      - './.env'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Tools PgAdmin
  pgadmin:
    container_name: pgadmin4
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

  # Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    depends_on:
      - db
    ports:
      - '4000:4000'
    env_file:
      - './.env'
