# DOCKER-COMPOSE
version: '3.9'
volumes:
  pgdata:
    driver: local
    name: pg_docker

services:
  db:
    image: postgres
    container_name: pg_db
    restart: always
    env_file:
      - './.env'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['postgres', '-c', 'log_statement=all']

  # pgadmin:
  #   container_name: pgadmin4
  #   restart: always
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@root.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'

  app:
    build:
      context: .
      dockerfile: DockerApi
    container_name: node_api
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgresql_tutorial
      POSTGRES_PORT: 5432
    command: ['./wait-for-postgres.sh', 'db', '--', 'npm', 'start']

  # react:
  #   build:
  #     context: ../../
  #     dockerfile: DockerReact
  #   container_name: learn_pg
  #   restart: always
  #   ports:
  #     - '3000:3000'
